---
apiVersion: api/v1
kind: Deployment
metadata:
  name: categories
  namespace: api
  labels:
    app: categories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: categories
  template:
    metadata:
      labels:
        app: categories
    spec:
      serviceAccountName: categories
      containers:
      - name: app
        image: ghcr.io/vlj91/categories:latest
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          successThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: categories
  namespace: api
  labels:
    app: categories
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: categories
