---
apiVersion: api/v1
kind: Deployment
metadata:
  name: events
  namespace: api
  labels:
    app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      serviceAccountName: events
      containers:
      - name: app
        image: ghcr.io/vlj91/events:latest
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          successThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: events
  namespace: api
  labels:
    app: events
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: events
